---
  - name: test the connectivity to target servers 
    hosts: localhost
    tasks: 
       - name: install git
         shell: pwd
         register: gitoutput
       - name: show the output
         debug:
           msg: "{{ gitoutput}}"
